POST http://127.0.0.1:8000/api/v1/auth/register
Accept: application/json
Content-Type: application/json


{
    "name": "uniforme 30",
    "email": "jav@gmail.com",
    "password": "321"
}

### Login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json


{
    "email": "jav@gmail.com",
    "password": "321"
}


### Perfil
GET http://127.0.0.1:8000/api/v1/auth/profile
Accept: application/json
Authorization: Bearer 2|kU6dms6Iv1vESvVNilznIhft3KVoXmCvXPn0wLSl262535fa



### Cerrar SEsion
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 2|kU6dms6Iv1vESvVNilznIhft3KVoXmCvXPn0wLSl262535fa